# Generated by Django 6.0.2 on 2026-04-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_code",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("platform_operator", "平台运营"),
                            ("enterprise_admin", "企业管理员"),
                            ("employee", "企业员工"),
                            ("guest", "游客"),
                        ],
                        default="guest",
                        max_length=20,
                        verbose_name="业务角色码",
                    ),
                ),
                (
                    "real_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="真实姓名"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="职位/职级"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "contact_wechat",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="微信"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ent_user_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户企业扩展",
                "verbose_name_plural": "用户企业扩展",
                "db_table": "ent_user_profile",
            },
        ),
    ]
