# Generated by Django 6.0.2 on 2026-04-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSmsCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("register", "注册"),
                            ("password_reset", "密码重置"),
                        ],
                        max_length=20,
                        verbose_name="业务类型",
                    ),
                ),
                ("expire_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "短信验证码",
                "verbose_name_plural": "短信验证码",
                "db_table": "auth_sms_code",
                "indexes": [
                    models.Index(fields=["phone", "type"], name="idx_phone_type"),
                    models.Index(fields=["expire_at"], name="idx_expire_at"),
                ],
            },
        ),
    ]
