# Generated by Django 6.0.2 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_authsmscode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enterprise_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="关联企业ID"),
        ),
    ]
