# Generated by Django 6.0.2 on 2026-04-09 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="企业全称")),
                (
                    "credit_code",
                    models.CharField(
                        max_length=18, unique=True, verbose_name="统一社会信用代码"
                    ),
                ),
                (
                    "legal_representative",
                    models.CharField(max_length=100, verbose_name="法人姓名"),
                ),
                (
                    "business_license",
                    models.CharField(max_length=500, verbose_name="营业执照URL"),
                ),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Logo地址"
                    ),
                ),
                ("industry_id", models.BigIntegerField(verbose_name="一级行业ID")),
                (
                    "sub_industry_id",
                    models.BigIntegerField(verbose_name="二级行业ID（末级）"),
                ),
                (
                    "category_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="主营业务品类ID"
                    ),
                ),
                ("province_id", models.BigIntegerField(verbose_name="省份ID")),
                ("region_id", models.BigIntegerField(verbose_name="市ID")),
                (
                    "tags",
                    models.JSONField(blank=True, null=True, verbose_name="业务标签"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="企业简介"),
                ),
                (
                    "auth_status",
                    models.CharField(
                        choices=[
                            ("UNCLAIMED", "未认领"),
                            ("PENDING", "审核中"),
                            ("VERIFIED", "已认证"),
                            ("REJECTED", "已拒绝"),
                        ],
                        default="UNCLAIMED",
                        max_length=20,
                        verbose_name="认证状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_enterprises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="企业管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "企业",
                "verbose_name_plural": "企业",
                "db_table": "ent_enterprise",
            },
        ),
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "已拒绝"),
                        ],
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "audit_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="审核原因/备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_records",
                        to="enterprise.enterprise",
                        verbose_name="关联企业",
                    ),
                ),
            ],
            options={
                "verbose_name": "审核记录",
                "verbose_name_plural": "审核记录",
                "db_table": "ent_audit_record",
            },
        ),
    ]
