# Generated by Django 6.0.2 on 2026-04-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="数据类别")),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                ("code", models.CharField(max_length=50, verbose_name="编码")),
                (
                    "parent_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="父级ID"
                    ),
                ),
                (
                    "industry_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联行业ID"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "主数据字典",
                "verbose_name_plural": "主数据字典",
                "db_table": "plat_master_data",
            },
        ),
    ]
