import request from './request'

export const getProfile = () => request.get('/plat-admin/profile/')
export const getDashboardStats = () => request.get('/plat-admin/dashboard/stats/')
export const getDashboardTrend = (params) => request.get('/plat-admin/dashboard/trend/', { params })
export const getAuditList = (params) => request.get('/plat-admin/audit/enterprise/', { params })
export const approveEnterprise = (id, data) => request.post(`/plat-admin/audit/enterprise/${id}/approve/`, data)
export const rejectEnterprise = (id, data) => request.post(`/plat-admin/audit/enterprise/${id}/reject/`, data)
export const getTenantList = (params) => request.get('/plat-admin/tenant/enterprise/', { params })
export const getTenantDetail = (id) => request.get(`/plat-admin/tenant/enterprise/${id}/`)
export const toggleTenantStatus = (id) => request.put(`/plat-admin/tenant/enterprise/${id}/toggle-status/`)
export const getTenantMembers = (id, params) => request.get(`/plat-admin/tenant/enterprise/${id}/member/`, { params })
export const createTenantMember = (id, data) => request.post(`/plat-admin/tenant/enterprise/${id}/member/`, data)
export const updateTenantMember = (entId, memberId, data) => request.put(`/plat-admin/tenant/member/${memberId}/`, data)
export const deleteTenantMember = (entId, memberId) => request.delete(`/plat-admin/tenant/member/${memberId}/`)
export const resetTenantMemberPassword = (memberId) => request.post(`/plat-admin/tenant/member/${memberId}/reset-password/`)
export const unbindTenantMember = (memberId) => request.post(`/plat-admin/tenant/member/${memberId}/unbind/`)
export const getContentOpportunities = (params) => request.get('/plat-admin/content/opportunity/', { params })
export const getContentOpportunityDetail = (id) => request.get(`/plat-admin/content/opportunity/${id}/`)
export const offlineContentOpportunity = (id, data) => request.put(`/plat-admin/content/opportunity/${id}/offline/`, data)
export const getContentFeeds = (params) => request.get('/plat-admin/content/feed/', { params })
export const getContentFeedDetail = (id) => request.get(`/plat-admin/content/feed/${id}/`)
export const offlineContentFeed = (id, data) => request.put(`/plat-admin/content/feed/${id}/offline/`, data)
export const getMasterDataList = (params) => request.get('/plat-admin/master-data/', { params })
export const createMasterData = (data) => request.post('/plat-admin/master-data/', data)
export const updateMasterData = (id, data) => request.put(`/plat-admin/master-data/${id}/`, data)
export const toggleMasterDataStatus = (id) => request.put(`/plat-admin/master-data/${id}/toggle-status/`)
export const getRoles = () => request.get('/plat-admin/role/')
export const getRoleDetail = (id) => request.get(`/plat-admin/role/${id}/`)
export const updateRolePermissions = (id, data) => request.put(`/plat-admin/role/${id}/permissions/`, data)
export const getSettings = () => request.get('/plat-admin/settings/')
export const updateSettings = (data) => request.put('/plat-admin/settings/', data)
