# Generated by Django 6.0.2 on 2026-04-09 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0002_masterdata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="动态内容")),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="图片URL数组"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "在线"), ("OFFLINE", "下线")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeds",
                        to="enterprise.enterprise",
                        verbose_name="发布人所属企业",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_feeds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "动态",
                "verbose_name_plural": "动态",
                "db_table": "feed_feed",
                "ordering": ["-created_at"],
            },
        ),
    ]
