# Generated by Django 6.0.2 on 2026-04-10 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprise", "0003_enterprise_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BUY", "采购"), ("SUPPLY", "供应")],
                        max_length=10,
                        verbose_name="商机类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="商机标题")),
                ("industry_id", models.BigIntegerField(verbose_name="一级行业ID")),
                ("sub_industry_id", models.BigIntegerField(verbose_name="二级行业ID")),
                ("category_id", models.BigIntegerField(verbose_name="业务品类")),
                ("province_id", models.BigIntegerField(verbose_name="省份ID")),
                ("region_id", models.BigIntegerField(verbose_name="市ID")),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="业务标签"),
                ),
                ("detail", models.TextField(verbose_name="详细描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "在线"), ("OFFLINE", "下线")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览量")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="", max_length=11, verbose_name="联系电话"
                    ),
                ),
                (
                    "contact_wechat",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="微信"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="enterprise.enterprise",
                        verbose_name="发布企业",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_opportunities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商机",
                "verbose_name_plural": "商机",
                "db_table": "opp_opportunity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "已发起"),
                            ("CONFIRMED", "已确认"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获取时间"),
                ),
                (
                    "getter_enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opp_contacts",
                        to="enterprise.enterprise",
                        verbose_name="获取方企业",
                    ),
                ),
                (
                    "getter_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opp_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="获取方用户",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_logs",
                        to="opportunity.opportunity",
                        verbose_name="涉及的商机",
                    ),
                ),
            ],
            options={
                "verbose_name": "商机联系记录",
                "verbose_name_plural": "商机联系记录",
                "db_table": "opp_contact_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
